import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { ArrowRightCircleIcon } from "@heroicons/react/24/solid";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col h-screen justify-center">
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <p className="text-2xl text-slate-200 font-bold text-center text-bold ">
              JWT AUTH
            </p>
          </div>
        </div>
        <div className="absolute bottom-0 gap-x-16 left-1/2 items-center flex justify-center">
          <button onClick={()=> router.push('/register')} className="group hover:opacity-100 duration-150 opacity-20 rounded-lg flex gap-x-4 relative -left-1/2 w-48 text-center items-center text-lg bottom-10 px-4 py-2 outline-gray-600 text-white">
            <div className="flex m-auto justify-center items-center gap-x-4">
              <p>register</p>
              <ArrowRightCircleIcon className="h-5 w-5 group-hover:translate-x-2 group-hover:text-slate-100 duration-200 text-white" />
            </div>
          </button>
          <button onClick={()=> router.push('/login')} className="rounded-lg group flex gap-x-4 duration-150 hover:opacity-100 w-48 opacity-20 items-center relative -left-1/2 text-lg bottom-10 px-4 py-2 outline-gray-600 text-white">
            <div className="flex m-auto justify-center items-center gap-x-4">
              <p>login</p>
              <ArrowRightCircleIcon className="h-5 w-5 group-hover:translate-x-2 group-hover:text-slate-100 duration-200 text-white" />
            </div>
          </button>
        </div>
      </main>
    </>
  );
}
